(defun CrearTarea(id numero cumplio parcial)
    (list :id id :numero numero :cumplio cumplio :parcial parcial)
)

(defun PrincipalTarea(id)
    ;(cargartarea "tareas.db")
    (setq opt 4)
    (loop (if (/= opt 0)
            (progn
                (run-shell-command "clear")
                (LetraTareas)
                (LetraMenuConfig "TAREA     ")
                (setq opt (read))
                (cond
                    ((= opt 1)
                        (run-shell-command "clear")
                        (LetraTareas)
                        (format t "~%~%*****Anadir Tarea*****~%")
                        (anadirtareas id)
                        (guardartarea "Archivos/tareas.db")
                    )
    
                    ((= opt 2)
                        (run-shell-command "clear")
                        (LetraTareas)
                        (format t "~%~%****tareas Registradas****~%")
                        (impTarea id)
                        (format t "~%Ingrese codigo de tarea a modificar: ")
                        (setq numTarea (read-line))
                        (setq cumplio (y-or-n-p "Cumplio[y/n]: "))
                        (updateTarea (whereTarea :numTarea numTarea :IdMateria id) :cumplio cumplio)
                        (guardarTarea "Archivos/tareas.db")
                    )
                )
            )
            (return 'fin)
        )       
    )   
)

